name: Build

on:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bun run prettier:verify

      - run: bun run compile

      - run: bun test
